nginx:
  image: lfurrea/nginx
  ports:
    - "80:80"
  labels:
    io.rancher.container.pull_image: always
node:
  image: lfurrea/mytutorialapp
  environment:
    HAB_MYTUTORIALAPP: 'message="${MY_MESSAGE}"'
  ports:
    - "8080"
  labels:
    io.rancher.container.pull_image: always
