nginx:
  image: lfurrea/nginx
  command:
  - "--bind"
  - "app:mytutorialapp.prod"
  ports:
    - "80:80"
    - "9638/udp"
    - 9631
  labels:
    io.rancher.container.pull_image: always
node:
  image: lfurrea/mytutorialapp
  command:
  - "--group"
  - "prod"
  environment:
    HAB_MYTUTORIALAPP: 'message="${MY_MESSAGE}"'
  ports:
    - "8080"
    - "9638/udp"
    - "9631"
  labels:
    io.rancher.container.pull_image: always
