node-initial:
  image: lfurrea/mytutorialapp
  command:
  - "--topology"
  - "leader"
  - "--group"
  - "prod"
  environment:
    HAB_MYTUTORIALAPP: 'message="${MY_MESSAGE}"'
    HAB_GOSSIP_SUBNET: "inet 10.42"
  ports:
    - "8080"
    - "9638/udp"
    - "9631"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name

node:
  image: lfurrea/mytutorialapp
  command:
  - "--topology"
  - "leader"
  - "--group"
  - "prod"
  - "--peer"
  - "app-node-initial-1"
  environment:
    HAB_MYTUTORIALAPP: 'message="${MY_MESSAGE}"'
    HAB_GOSSIP_SUBNET: "inet 10.42"
  ports:
    - "8080"
    - "9638/udp"
    - "9631"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    
nginx:
  image: lfurrea/nginx
  command:
  - "--bind"
  - "app:mytutorialapp.prod"
  - "--peer"
  - "app-node-initial-1"
  environment:
    HAB_GOSSIP_SUBNET="inet 10.42"
  ports:
    - "80:80"
    - "9638/udp"
    - 9631
  labels:
    io.rancher.container.pull_image: always