nginx:
  image: lfurrea/nginx:0.2.1
  links:
    - node1:node1
  ports:
    - "80:80"

node1:
  image: lfurrea/mytutorialapp
  environment:
    HAB_MYTUTORIALAPP: 'message="${MY_MESSAGE}"'
  ports:
    - "8080"
